Parameters:
    IncludeKonga:
      Description: WebServer EC2 instance type (has default, AllowedValues)
      Type: String
      Default: t2.small
      AllowedValues:
        - t1.micro
        - t2.nano
        - t2.micro
        - t2.small




Resources:
  # Security Groups

  KongSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: "Kong ECS"
      GroupDescription: "Security Group for Kong ECS (US East)"
      VpcId: !Ref SelectedVPC
      SecurityGroupIngress:

  DabaseSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: "Kong RDS"
      GroupDescription: "Security Group for Kong RDS (US East)"
      VpcId: !Ref SelectedVPC
      SecurityGroupIngress:


  KongDatabase:
    Type: "AWS::RDS::DBInstance"
    Properties:

      AllocatedStorage: "20 GB"
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: "2 Days"
      DBInstanceClass: "db.t2.micro"
      DBName: "kong"
      # Eventually, specify a Snapshot as a parameter
      # This will enable importing of
      #DBSnapshotIdentifier: "TODO PARAM" # If provided, DBName is ignored
      DeletionPolicy: "Snapshot"
      Engine: "postgres"
      EngineVersion: "9.6.6"
      MasterUsername: "TODO PARAM"
      MasterUserPassword: !Ref KeyName
      PubliclyAccessible: true
      # For Read replicas in the future! See docs for more info
      # SourceDBInstanceIdentifier: String
      VPCSecurityGroups:
        - !ImportValue PersonalPostgresIngress
        - !Ref DabaseSecurityGroup


# SSL Certificate

# S3 Bucket

# Create database

# Create security group(s) ?? Which ones, etc?

# Add an instance to the pool
